//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongHaven
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid guid_id { get; set; }
        public string content { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.Guid> fk_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
