//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongHaven
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public System.Guid guid_id { get; set; }
        public string nvc_title { get; set; }
        public string nvc_album { get; set; }
        public string nvc_artist { get; set; }
        public int int_number_of_plays { get; set; }
        public System.DateTime dt_created_date { get; set; }
        public Nullable<System.DateTime> dt_last_played_date { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
